### ISSUE TITLE
Make a tutorial for the Dlang Tour

### ISSUE THREAD

**Issue by wilzbach** [MaikKlein/VulkanTriangleD#1]
If you want, we are still searching for people to provide a nice &interactive intro tutorial to game programming in D.

See e.g. https://github.com/stonemaster/dlang-tour/issues/27

**Comment by MaikKlein** [comment]
I don't think that I am qualified to do this, also gamedev is probably too broad. I am working on a game engine, maybe when it is fleshed out I could create an interactive tutorial.
