### ISSUE TITLE
It's not allowed to transition swapchain images when you haven't acquired them

### ISSUE THREAD

**Issue by ratchetfreak** [MaikKlein/VulkanTriangleD#2]
https://github.com/MaikKlein/VulkanTriangleD/blob/master/source/app.d#L354-L393

https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain

> Use of a presentable image must occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. **This includes transitioning the image layout and rendering commands.**

You can however transition from UNDEFINED [in the pre-render barrier](https://github.com/MaikKlein/VulkanTriangleD/blob/master/source/app.d#L814) which is allowed.

Another option is to set the initialLayout of the color attachment to UNDEFINED and the finalLayout to PRESENT and add subpass dependencies from and to external as needed to fold those transitions into the renderpass.

**Comment by MaikKlein** [comment]
Oops I remember reading this at some point but I forgot about it because I don't get any validation errors.

I guess I could just loop over all images with `vkAcquireNextImageKHR` and transition them from undefined to present.

**Comment by ratchetfreak** [comment]
That's not required actually. You can always transition away from undefined no matter what the previous layout was if you don't care about the data still in the image. Which you don't because the next operation on that image is a clear on begin renderpass .

**Comment by MaikKlein** [comment]
Okay so if I understood you correctly

https://github.com/MaikKlein/VulkanTriangleD/blob/master/source/app.d#L774

I leave it in undefined, transition it to color in my renderloop, then I switch it to present?

**Comment by ratchetfreak** [comment]
Yep

**Comment by MaikKlein** [comment]
Okay that is even simpler and thanks for explaining it to me.
