### ISSUE TITLE
Using memoryTypeBits in wrong place

### ISSUE THREAD

**Issue by Ka-lua** [MaikKlein/VulkanTriangleD#3]
Manuel König here, just found this when adding window resize capabilities to your example:

When you query the vertexMemoryTypeBits, you use memoryTypeBits accidentally in line 544 instead of vertexMemoryTypeBits.

Cheers,

Manuel

**Comment by MaikKlein** [comment]
Fixed https://github.com/MaikKlein/VulkanTriangleD/commit/a692bec19bd67cf3d1c48dce37d5e0883573e52e

Thanks for reporting the bug.
